version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
      exclude:
        - "dash14/buildcage*"
  
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14

  - package-ecosystem: "docker"
    directories:
      - "/docker"
      - "/test"
      - "/test/test-dns"
      - "/test/test-server"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
