engineStrict: true
trustPolicy: no-downgrade
minimumReleaseAge: 20160 # 2 weeks
minimumReleaseAgeExclude:
  - '@sigstore/bundle@5.0.0'
  - '@sigstore/core@4.0.0'
  - '@sigstore/tuf@5.0.0'
  - '@sigstore/verify@4.0.0'
  - '@tufjs/models@5.0.0'
  - tuf-js@6.0.0
