#!/command/with-contenv sh
set -e

echo "init-cni-bridge: creating sandbox0 bridge..."

if ! ip link show sandbox0 >/dev/null 2>&1; then
  ip link add sandbox0 type bridge
  ip addr add 172.20.0.1/24 dev sandbox0
  ip link set sandbox0 up
fi
ip link set lo up

echo "init-cni-bridge: sandbox0 up at 172.20.0.1/24"
