/**
 * Corefile generator for the `inspect` engine.
 *
 * The resolver is a security boundary: a forwarded query reaches an attacker's
 * nameserver with no connection ever made, so whatever it will look up is what
 * a build can leak. Its scope must match the rules exactly, which is why this
 * engine uses CoreDNS (regex views) over dnsmasq (suffix matching, which could
 * only widen `abc*.amazonaws.com` to `/amazonaws.com/`).
 *
 * A name outside the allowlist is answered with the proxy's own address, not
 * NXDOMAIN, so the build connects to the proxy and its full URL is recorded
 * before being denied. The proxy resolves through this same resolver, so the
 * two never disagree about where a name points.
 */

import type { UrlRule } from "./url-rules.ts";
import { wildcardToRegexPartial } from "./partial-wildcard.ts";

export interface CorednsConfigOptions {
  /** Host rules (`host:port` wildcards). Only the host half is used here. */
  httpsRules?: string[];
  httpRules?: string[];
  /** TLS rules. Their names have to resolve too, even though they are not inspected. */
  tlsRules?: string[];
  urlRules?: UrlRule[];
  /** Address a non-allowlisted name resolves to, so it lands on the proxy. */
  proxyAddress: string;
  /** Upstream resolvers an allowlisted name is forwarded to. */
  upstreams: string[];
  /** TTL for the synthesised answers. */
  ttlSeconds?: number;
  /**
   * `audit` refuses nothing, so it has no allowlist to enforce: every name is
   * forwarded and recorded. Defaults to `restrict`.
   */
  mode?: "audit" | "restrict";
}

export interface GeneratedCorednsConfig {
  config: string;
  /** Rules whose host could not be derived (`~` regex with a non-literal host). */
  warnings: string[];
}

/**
 * Escape a regex for a CEL string literal.
 *
 * CEL rejects `\.` as an invalid character escape, so every backslash has to
 * be doubled to survive into the regex engine. Substituting only the dots
 * would be wrong: the host compiler escapes every one of `.+^$()[]{}|\`, and a
 * `~` rule may contain any of them.
 */
export function escapeForCel(regex: string): string {
  return regex.replace(/\\/g, "\\\\");
}

/** The host half of a `host:port` wildcard, as a regex. */
function hostRegexOfHostRule(pattern: string): string {
  const combined = wildcardToRegexPartial(pattern);
  return combined.slice(0, combined.lastIndexOf(":"));
}

/** The host half of a compiled URL rule, as a regex. */
function hostRegexOfUrlRule(rule: UrlRule): string | null {
  if (!rule.authorityRegex) return null;
  // authorityRegex is `^<hostRegex>:<port>$`.
  const inner = rule.authorityRegex.slice(1, -1);
  const colonIndex = inner.lastIndexOf(":");
  return colonIndex === -1 ? null : inner.slice(0, colonIndex);
}

/**
 * Generate a Corefile from buildcage's rules.
 *
 * @throws {Error} if a host rule has invalid wildcard syntax
 */
export function generateCorednsConfig(options: CorednsConfigOptions): GeneratedCorednsConfig {
  const { proxyAddress, upstreams, ttlSeconds = 60, mode = "restrict" } = options;
  const warnings: string[] = [];
  const hostRegexes: string[] = [];

  // Audit refuses nothing, so every name resolves for real; answering locally
  // would point them all at the proxy and reach no origin at all.
  if (mode === "audit") {
    const lines = [
      "# Generated by buildcage. Do not edit.",
      "",
      "# audit enforces nothing, so every name resolves for real. The queries are",
      "# still recorded, which is how a name that was only looked up shows up in",
      "# the report alongside the ones that were connected to.",
      ". {",
      `    forward . ${upstreams.join(" ")}`,
      '    log . "buildcage dns allowed name={name}"',
      "    errors",
      "}",
      "",
    ];
    return { config: lines.join("\n"), warnings };
  }

  const add = (regex: string | null, raw: string) => {
    if (!regex) {
      warnings.push(
        `Rule ${JSON.stringify(raw)} has no derivable host, so the names it targets will not resolve. ` +
          `Add a matching allowed_https_rules entry for the host it targets.`,
      );
      return;
    }
    if (!hostRegexes.includes(regex)) hostRegexes.push(regex);
  };

  for (const rule of options.httpsRules ?? []) add(hostRegexOfHostRule(rule), rule);
  for (const rule of options.httpRules ?? []) add(hostRegexOfHostRule(rule), rule);
  for (const rule of options.tlsRules ?? []) add(hostRegexOfHostRule(rule), rule);
  for (const rule of options.urlRules ?? []) add(hostRegexOfUrlRule(rule), rule.raw);

  const lines: string[] = ["# Generated by buildcage. Do not edit.", ""];

  if (hostRegexes.length > 0) {
    // A queried name arrives with its trailing dot, hence the `[.]` before the
    // anchor. Alternation is used rather than one block per rule so a name is
    // matched against the whole allowlist in one pass.
    const alternation = hostRegexes.map((r) => `(${r})`).join("|");
    lines.push(
      "# Allowlisted names resolve for real. The expression is the same host",
      "# pattern the proxy rules are built from, so the two cannot drift apart.",
      ". {",
      "    view allowlist {",
      `      expr name() matches '^(${escapeForCel(alternation)})[.]$'`,
      "    }",
      `    forward . ${upstreams.join(" ")}`,
      '    log . "buildcage dns allowed name={name}"',
      "    errors",
      "}",
      "",
    );
  }

  lines.push(
    "# Everything else resolves to the proxy and is answered locally, so the",
    "# query never leaves and the request still arrives somewhere its full URL",
    "# can be recorded before being denied.",
    ". {",
    "    template IN A {",
    `      answer "{{ .Name }} ${ttlSeconds} IN A ${proxyAddress}"`,
    "    }",
    // NOERROR with an empty answer (NODATA), not NXDOMAIN: this host has no
    // IPv6 presence to answer AAAA with, but NXDOMAIN claims the name itself
    // does not exist. musl's getaddrinfo(AF_UNSPEC) takes that literally and
    // discards the valid A answer above along with it, so a build under
    // Alpine (BusyBox wget, apk, ...) fails outright instead of falling back
    // to the A record like every other resolver does.
    "    template IN AAAA {",
    "    }",
    '    log . "buildcage dns denied name={name}"',
    "    errors",
    "}",
    "",
  );

  return { config: lines.join("\n"), warnings };
}
