name: Image Security Scan
run-name: Image Security Scan (${{ github.ref_name }})

on:
  schedule:
    # Monthly on the 1st at 00:00 UTC
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - engine: transparent
            dockerfile: setup/docker/transparent/Dockerfile
          - engine: explicit
            dockerfile: setup/docker/explicit/Dockerfile
          - engine: proxy
            dockerfile: run/docker/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        env:
          DOCKER_BUILD_CHECKS_ANNOTATIONS: false
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          load: true
          tags: buildcage-${{ matrix.engine }}:scan

      - name: Scan image with Trivy
        if: github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: buildcage-${{ matrix.engine }}:scan
          ignore-unfixed: true
          trivyignores: .trivyignore
          scanners: vuln
          format: sarif
          output: trivy-results-${{ matrix.engine }}.sarif
          severity: CRITICAL,HIGH

      - name: Upload Trivy scan results to GitHub Security
        if: github.ref == 'refs/heads/main'
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: trivy-results-${{ matrix.engine }}.sarif
          category: ${{ matrix.engine }}

      - name: Scan image with Trivy
        if: github.ref != 'refs/heads/main'
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: buildcage-${{ matrix.engine }}:scan
          ignore-unfixed: true
          trivyignores: .trivyignore
          scanners: vuln
          format: table
