name: Test
run-name: Test (${{ github.ref_name }})

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  unit_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: test (unit)
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run unit tests
        run: make test_unit

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - mode: audit
            proxy_mode: audit
            test_dockerfile: test/Dockerfile.audit
            assert_script: ./test/assert-audit-mode.sh
            builder_name: buildcage-audit
          - mode: restrict
            proxy_mode: restrict
            test_dockerfile: test/Dockerfile.restrict
            assert_script: ./test/assert-restrict-mode.sh
            builder_name: buildcage-restrict

    name: test (${{ matrix.mode }})

    env:
      COMPOSE_FILE: compose.yml:compose.test.yml

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build containers
        run: docker compose build

      - name: Start containers
        env:
          PROXY_MODE: ${{ matrix.proxy_mode }}
          BUILDER_NAME: ${{ matrix.builder_name }}
        run: docker compose up -d --wait

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        with:
          driver: remote
          endpoint: docker-container://${{ matrix.builder_name }}

      - name: Build test image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        env:
          DOCKER_BUILD_CHECKS_ANNOTATIONS: false
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: test
          file: ${{ matrix.test_dockerfile }}
          push: false
          no-cache: true
          load: true
          tags: buildcage-test

      - name: Show logs
        if: always()
        env:
          BUILDER_NAME: ${{ matrix.builder_name }}
          INPUT_BUILDER_NAME: ${{ matrix.builder_name }}
        run: node report/main.mjs ./compose.yml || true

      - name: Run assertions
        run: ${{ matrix.assert_script }}

      - name: Cleanup
        if: always()
        env:
          BUILDER_NAME: ${{ matrix.builder_name }}
        run: docker compose down -v --rmi all 2>/dev/null || true
